<?php 
//1 = attack power(attack damage with weapon), 
//2 = defend power(decrease and block incoming damages), 
//3 = magical power(casting magic spells and heal spells), 
//4 = thief power(multifier for gold stealing in a battle).

$races_array = array (
'Alfs'		=> array (5,15,15,10,5,'Small hairy thieves not bad for these tinny creatures'),
'Asumodus'	=> array (15,5,15,10,5,'What is the meaning of magic when you can chop his head off'),
'Barbarian'	=> array (15,15,10,5,5,'Fearless the best for hand to hand combat'),
'Beasties'	=> array (10,10,10,10,10,'Master of the Beast gets help from the animals to steel gold in an fight'),
'Centaurs'	=> array(20,5,5,15,5,'They are quite attune with nature as are Elves, and develop bonds with nature'),
'Dracoids'	=> array (10,5,15,15,5,'Masters of mystics and defenders'),
'Drow'		=> array (15,10,15,5,5,'Racial enemies of elves that dwell in the network of caves underground known as Underdark'),
'Dwarf'		=> array (10,15,15,5,5,'An strong races with not that much thieving and mystics but more combat action'),
'Elves'		=> array (5,5,15,20,5,'With help of magic they are very strong in battle too'),
'Eurodite'	=> array (5,10,20,10,5,'The opposite of the Barbarian with great magical powers'),
'Faeries'		=> array (0,0,25,20,5,'With their magic good and thief abilities they can become and masters of mystics'),
'Gnome'		=> array (25,20,0,0,5,'A bit more power at the cost of mystics'),
'Goblins'		=> array (20,15,10,0,5,'Battle and stand line very strong race'),
'Human'		=> array (20,15,5,5,5,'A bit knowing everything races'),
'Humeves'	=> array (20,0,20,5,5,'Half human and half elve makes this races a bit stronger to cast magic spells then the humans'),
'Hydroids'	=> array (0,25,20,0,5,'Chemical creatures that gives light in the dark'),
'Minotaurs'	=> array (25,10,10,5,5,'Among the largest bipedal creatures topping over eight feet with horns cresting out of the skull.'),
'Ogre'		=> array (0,25,0,20,5,'Strength is key to succes'),
'Paladin'		=> array (25,5,5,10,5,'Blessed warrior defending and mystics'),
'Reptasar'	=> array (25,25,0,0,0,'An reptile race from dark wetlands'),
'Sacromancer'	=> array (0,0,25,25,0,'One of the most powerful sacrificing mystic race'),
'Satyrs'		=> array (25,10,10,5,5,'These goat-mens do not wander far from their home and are only offensive towards others intruders'),
'Troll'		=> array (15,15,15,0,5,'Strong attack power but weak at d�fense'),
'Undead'		=> array (0,0,0,25,25,'How can you kill something that cant live.'),
'Wemics'		=> array (25,10,10,0,5,'Their body is of a lion and their upper torso like Centaurs is humanoid.'),
'Pseudo Dragon'	=> array (10,5,20,10,5, 'They have a slightly more solid build than full sized dragons and they can be Blue, Grey, Green, or White in color.'),
);
?>