<?php 
$Weapons = array(
'Fly bat',
'Rusty Fork',
'Old Knife',
'Damaged Sword',
'Broken Scythe',
'Tinny Spear',
'Headless Mace',
'Wood Staff',
'Tiger Claw',
'Iron Knife',
'Short Sword',
'Steel Lance',
'Axe',
'Claymore',
'Butterfly Sword',
'Ancient Hydra',
'Viashino Cutthroat',
'Longsword',
'Long Spear',
'Blessed Hammer',
'Giant Staff',
'Kings Sword',
'Double Axe',
'Lance Axe',
'Fire Sword',
'Poisoned Mace',
'Mighty Dirk',
'Ancient Wand',
'Ornate Longsword',
'Godzilla Tooth',
'Unknown Dagger',
'Revengers Hammer',
'Battle Knife',
'War Spear',
'Double Staff',
'Faceless Axe',
'Ninja Sword',
'Samurai Longsword',
'Superior Wand',
'Slaughter Hammer',
'Element Axe',
'Dragon tooth Mace',
'Blessed Battle lance',
'Superior War hammer',
'Kings Martel',
'Lightning Lance',
'Grim ripper Longsword',
'Shockering Staff',
'Automatic Great bow',
'Dino War mace',
'Skin Stripper',
'Brain Cracker',
'Soul bender War lance',
'Ancient Katana',
'Flying Sword saw',
'Throwing War hammer',
'Piercing War dagger',
'Four sided War axe',
'Yelling Grandmother',
'Demon kings Torment',
'Grim reaper Scythe',
'Godzillas Spiked Tail',
'Demons Jawbreaker',
'Life Taker',
'Force Charger',
'Four yard War scythe',
'Stealth Longsword',
'Eartbreaker War hammer',
'Spirit Katana',
'Blessed Cross sword',
'Chilled War wand',
'Heavens Guard sword',
'Guided War bow',
'Giant War Martel',
'Dark Revengers Knife',
'Superior War hammer',
'Ancient War sword',
'Excalibur of Giants',
'Superior lance of Piercing',
'Poisoned Double bow',
'Giant Nunjakos',
'Guided Ninja Stars',
'Twenty Feet War lance',
'Excalibur of Piercing',
'Revengers Slaughter Knife',
'Superior War martel',
'Ancient Longsword',
'Thunder gods War martel',
'Demons Grim Mace',
'Hell Councils War wand',
'Stone keepers Chaos staff',
'Elemental Stinger sword',
'Hells Executors Head axe',
'Elemental Excalibur',
'Thors War martel',
'Chaos Scythe of Blinds',
'Swordcrakers Scissors',
'Ancient Diamond Sword',
'Soul raiders Chaos lance ',
'Avengers Chaos Axe',
'Sword of Chaos',
'Sword of Burning Souls',
'Supermonkeys War lance',
'Giants Five Feet Long Sword',
'Penetrators Chaos sword',
'Longsword of Five Elements',
'Thundermartel of Guardian Angel',
'Choassword of Shadows',
'Spiked Boomerang of Elements',
'Diamond Sharpened Katana',
'Choasstaff of Heavenly Wizards',
'Sentries Doom Shadow Wand',
'Instant Death Dagger of Piercing',
'Frozen Chaos Longsword',
'Dracula Teeth Spiked Doom Mace',
'Superior Chaos Spear of Light',
'Demon Blood Painted Chaosstaff',
'Forbidden Sword of Slaughters',
'Mulit Missile Chaosbow',
'Diamond Lance of Elements',
'Instant Dead Dagger of Piercing',
'Golden Chaos Hammer of Pain',
'Lightning Charged Warbow',
'Superior Tesla Grimsword',
'Thundermartel of Flat Crush',
'Demon Scythe of Limits',
'Shrinking Demon Wand',
'Hunterbow of Precision',
'Shadowbow With guided Arrows',
'Seputurian Chaoslance',
'Voodoo Grimrip Wand',
'Thunderlance of Shadows',
'Holy Warscepter of Heavens',
'Longsword of Hellgate Guard',
'Full Duplex Diamond Chaosmartel',
'Forcefeeded Bonehammer of Uri',
'Lamas Gigantic Doublesword',
'Chaosscythe of Elements',
'Shadow Razor Daggers',
'Foursided Lightningmartel',
'Godhammer of Earthquake',
'Diamond Ninja Stars',
'Dagger of Eternal Virgin',
'Ancient Grim Bone of Elements',
'Poisoned Suicide Dagger',
'Superior Longsword of Defrocks',
'Ultimate Avengers Longsword',
'Elemental Shadowspear',
'Sunfire Diamond Sword',
'Shadowlance of Moonlight',
'Walhallas Chaostusk',
'Shadowkatana of Assassins',
'Elemental Spearmace',
'Chaoslongsword of Terror',
'Hybrid Fugu Legendkatana',
'Sword of the Sixth Element'
);
?>