<?php 
$races_array = array (
'Alfs'		=> array (1,5,5,5,3,'Small hairy thieves not bad for these tinny creatures'),
'Asumodus'	=> array (14,8,6,4,2,'What is the meaning of magic when you can chop his head off'),
'Barbarian'	=> array (13,8,8,2,2,'Fearless the best for hand to hand combat'),
'Beasties'	=> array (10,8,4,3,3,'Master of the Beast gets help from the animals to steel gold in an fight'),
'Centaurs'	=> array(23,2,8,9,2,'They are quite attune with nature as are Elves, and develop bonds with nature'),
'Dracoids'	=> array (4,1,9,9,1,'Masters of mystics and defenders'),
'Drow'		=> array (16,3,7,7,3,'Racial enemies of elves that dwell in the network of caves underground known as Underdark'),
'Dwarf'		=> array (5,7,6,4,3,'An strong races with not that much thieving and mystics but more combat action'),
'Elves'		=> array (6,6,4,7,3,'With help of magic they are very strong in battle too'),
'Eurodite'	=> array (18,4,4,8,3,'The opposite of the Barbarian with great magical powers'),
'Faeries'		=> array (7,2,6,8,3,'With their magic good and thief abilities they can become and masters of mystics'),
'Gnome'		=> array (9,7,7,3,3,'A bit more power at the cost of mystics'),
'Goblins'		=> array (8,8,7,4,1,'Battle and stand line very strong race'),
'Human'		=> array (0,6,6,6,2,'A bit knowing everything races'),
'Humeves'	=> array (20,5,6,7,2,'Half human and half elve makes this races a bit stronger to cast magic spells then the humans'),
'Hydroids'	=> array (11,7,5,3,3,'Chemical creatures that gives light in the dark'),
'Minotaurs'	=> array (21,9,9,1,1,'Among the largest bipedal creatures topping over eight feet with horns cresting out of the skull.'),
'Ogre'		=> array (2,8,5,4,3,'Strength is key to succes'),
'Paladin'		=> array (12,5,5,8,2,'Blessed warrior defending and mystics'),
'Reptasar'	=> array (19,2,8,5,3,'An reptile race from dark wetlands'),
'Sacromancer'	=> array (15,3,7,8,2,'One of the most powerful sacrificing mystic race'),
'Satyrs'		=> array (24,7,7,3,2,'These goat-mens do not wander far from their home and are only offensive towards others intruders'),
'Troll'		=> array (3,9,2,7,2,'Strong attack power but weak at d�fense'),
'Undead'		=> array (17,8,9,1,2,'How can you kill something that cant live.'),
'Wemics'		=> array (22,8,7,2,3,'Their body is of a lion and their upper torso like Centaurs is humanoid.'),
'Pseudo Dragon'	=> array (24,5,7,9,3, 'They have a slightly more solid build than full sized dragons and they can be Blue, Grey, Green, or White in color.'),
);
?>