<?php 
$Healspells = array(
'Minor Rest',
'Minor Blessing',
'Health Breath',
'Minor Healing',
'Minor Recovery',
'Major Rest',
'Major Blessing',
'Major Healing',
'Major Recovery',
'Minor Rejuvenation',
'Major Rejuvenation',
'Mega Healing',
'Mega Recovery',
'Mega Rejuvenation',
'Super Healing',
'Super Recovery',
'Super Rejuvenation',
'Blood Lust',
'Soul Survivor',
'Guardian Breath',
'Guardian Health',
'Guardian Breath',
'Guardian Health',
'Guardian Salvation',
'Guardian Resurrection',
'Guardian Life',
'Guardian Rebirth',
'Guardian Heaven',
'Angels Breath',
'Angels Health',
'Angels Salvation',
'Angels Resurrection',
'Angels Life',
'Angels Rebirth',
'Angels Heaven',
'Heavenly Health',
'Heavenly Salvation',
'Heavenly Life',
'Heavenly Breath',
'Heavenly Resurrection',
'Sexy Bitches',
'Nurse from heaven',
'Angels of Big Resurrection',
'Angels of Life rain',
'Reborn Angels',
'Super Angels',
'Heavenly Mega Health',
'Heavenly Mega Salvation',
'Heavenly Mega Life',
'Heavenly Mega Breath',
'Superior Angel of Life',
'Superior Angel of Rebirth',
'Immortality'
);
?>